apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dime-app.fullname" . }}
  labels:
    {{- include "dime-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dime-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dime-app.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "dime-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- end }}
          {{- if or .Values.env .Values.secretEnv }}
          envFrom:
          {{- if .Values.env }}
            - configMapRef:
                name: {{ include "dime-app.fullname" . }}-env
          {{- end }}
          {{- if .Values.secretEnv }}
            - secretRef:
                name: {{ include "dime-app.fullname" . }}-secret
          {{- end }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.tmpVolume.enabled }}
          volumeMounts:
            {{- toYaml .Values.tmpVolume.mounts | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          {{- if not $.Values.tmpVolume.enabled }}
          volumeMounts:
          {{- end }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.tmpVolume.enabled }}
      volumes:
        {{- range .Values.tmpVolume.mounts }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}
      {{- end }}
      {{- with .Values.volumes }}
      {{- if not $.Values.tmpVolume.enabled }}
      volumes:
      {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
