services:
  grafana:
    image: grafana/grafana-oss:11.1.4
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_DOMAIN: ${SERVICE_HOST}
    ports:
      - "127.0.0.1:${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      default:
        aliases:
          - ${SERVICE_HOST}

networks:
  default:
    name: ${SHARED_NETWORK}
    external: true

volumes:
  grafana_data:
    name: ${SERVICE_VOLUME}
