domain: ""
ingressClassName: traefik
ingress:
  annotations: {}
  tls:
    enabled: false
    secretName: ""
certificate:
  enabled: false
  issuerRef:
    name: ""
    kind: ClusterIssuer
backend:
  host: ""
  port: 80
service:
  port: 80
