apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-route.fullname" . }}
  labels:
    {{- include "external-route.labels" . | nindent 4 }}
spec:
  {{- if regexMatch "^([0-9]{1,3}\\.){3}[0-9]{1,3}$" .Values.backend.host }}
  type: ClusterIP
  {{- else }}
  type: ExternalName
  externalName: {{ .Values.backend.host }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
