services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "127.0.0.1:${PORTAINER_HTTP_PORT}:9000"
      - "127.0.0.1:${PORTAINER_HTTPS_PORT}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      default:
        aliases:
          - ${SERVICE_HOST}

networks:
  default:
    name: ${SHARED_NETWORK}
    external: true

volumes:
  portainer_data:
    name: ${SERVICE_VOLUME}
