---
- name: Deploy shared services
  hosts: "{{ target_server | default('all') }}"
  become: yes

  vars_files:
    - ../data/shared-services.yml

  tasks:
    - name: Deploy subscribed shared services
      include_tasks: ../tasks/deploy-shared-service-subscription.yml
      loop: "{{ shared_services | default([]) }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        shared_service_subscription: "{{ item }}"
