---
- name: Deploy shared services
  hosts: "{{ target_server | default('all') }}"
  become: yes

  vars_files:
    - ../config/shared-services/catalog.yml

  tasks:
    - name: Deploy subscribed shared services
      include_tasks: ../tasks/shared-services/deploy-shared-service-subscription.yml
      loop: "{{ shared_services | default([]) }}"
      loop_control:
        loop_var: shared_service_subscription_item
        label: "{{ shared_service_subscription_item.name }}"
      vars:
        shared_service_subscription: "{{ shared_service_subscription_item }}"

    - name: Stop unsubscribed shared services
      include_tasks: ../tasks/shared-services/cleanup-unsubscribed-shared-services.yml
