---
- name: Create nginx config for {{ app.name }} ({{ env_item.key }})
  template:
    src: ../templates/nginx-app.j2
    dest: "/etc/nginx/sites-available/{{ app.name }}-{{ env_item.key }}.conf"
    mode: '0644'
  vars:
    domain: "{{ env_item.value.domain }}"
    backend_port: "{{ env_item.value.port | default(omit) }}"
    ssl_enabled: "{{ ssl_enabled | default(false) }}"
  loop: "{{ environments_to_use }}"
  loop_control:
    loop_var: env_item

- name: Enable {{ app.name }} {{ env_item.key }}
  file:
    src: "/etc/nginx/sites-available/{{ app.name }}-{{ env_item.key }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ app.name }}-{{ env_item.key }}.conf"
    state: link
  loop: "{{ environments_to_use }}"
  loop_control:
    loop_var: env_item